-- Database export: db_sistema_veterinario
-- Date: 2026-08-05 16:54:12
-- Generated by DBX

-- Database setup
CREATE DATABASE IF NOT EXISTS `db_sistema_veterinario` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `db_sistema_veterinario`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `species`;

CREATE TABLE `species` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `medicines`;

CREATE TABLE `medicines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 0,
  `unit_cost` decimal(10,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `services`;

CREATE TABLE `services` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `category` enum('consulta','vacunacion','cirugia','estetica','otro') DEFAULT 'consulta',
  `base_price` decimal(10,2) NOT NULL,
  `duration_minutes` int(11) DEFAULT 30,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `branches`;

CREATE TABLE `branches` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` varchar(200) NOT NULL,
  `city` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `owners`;

CREATE TABLE `owners` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) NOT NULL,
  `address` varchar(200) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `type_documento` varchar(50) DEFAULT NULL,
  `n_documento` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `breeds`;

CREATE TABLE `breeds` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `species_id` bigint(20) unsigned NOT NULL,
  `name` varchar(60) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_species_breed` (`species_id`,`name`),
  CONSTRAINT `1` FOREIGN KEY (`species_id`) REFERENCES `species` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vaccine_types`;

CREATE TABLE `vaccine_types` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `base_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `species_id` bigint(20) unsigned DEFAULT NULL COMMENT 'si aplica solo a una especie',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `species_id` (`species_id`),
  CONSTRAINT `1` FOREIGN KEY (`species_id`) REFERENCES `species` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` bigint(20) unsigned DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `type_documento` varchar(50) DEFAULT NULL,
  `n_documento` varchar(50) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `avatar_public_id` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `branch_id` (`branch_id`),
  CONSTRAINT `1` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `invoices`;

CREATE TABLE `invoices` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `invoiceable_type` enum('cita','vacuna','surgiere') NOT NULL,
  `invoiceable_id` bigint(20) unsigned NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  `total` decimal(10,2) NOT NULL,
  `remaining_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `status` enum('pendiente','pagado','parcial','anulado') DEFAULT 'pendiente',
  `issued_at` date NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_invoiceable` (`invoiceable_type`,`invoiceable_id`),
  KEY `idx_invoices_owner` (`owner_id`),
  CONSTRAINT `1` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `pacientes`;

CREATE TABLE `pacientes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `owner_id` bigint(20) unsigned NOT NULL,
  `species_id` bigint(20) unsigned NOT NULL,
  `breed_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` enum('macho','hembra','desconocido') DEFAULT 'desconocido',
  `color` varchar(50) DEFAULT NULL,
  `weight` decimal(6,2) DEFAULT NULL COMMENT 'ultimo peso registrado, historial real en vital_signs',
  `photo` varchar(255) DEFAULT NULL,
  `photo_public_id` varchar(255) DEFAULT NULL,
  `medical_notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `species_id` (`species_id`),
  KEY `breed_id` (`breed_id`),
  KEY `idx_pacientes_owner` (`owner_id`),
  CONSTRAINT `1` FOREIGN KEY (`owner_id`) REFERENCES `owners` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`species_id`) REFERENCES `species` (`id`),
  CONSTRAINT `3` FOREIGN KEY (`breed_id`) REFERENCES `breeds` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `veterinarian_schedules`;

CREATE TABLE `veterinarian_schedules` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `veterinarian_id` bigint(20) unsigned NOT NULL,
  `day_of_week` tinyint(4) NOT NULL COMMENT '0=Domingo ... 6=Sabado',
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_vet_day_start` (`veterinarian_id`,`day_of_week`,`start_time`),
  CONSTRAINT `1` FOREIGN KEY (`veterinarian_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payments`;

CREATE TABLE `payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint(20) unsigned NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `advance_amount` decimal(10,2) DEFAULT 0.00 COMMENT 'adelanto, si aplica',
  `payment_method` enum('efectivo','tarjeta','transferencia','otro') NOT NULL,
  `status` enum('pendiente','pagado','anulado') DEFAULT 'pendiente',
  `paid_at` datetime NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_payments_invoice` (`invoice_id`),
  CONSTRAINT `1` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `citas`;

CREATE TABLE `citas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `veterinarian_id` bigint(20) unsigned NOT NULL,
  `service_id` bigint(20) unsigned DEFAULT NULL,
  `created_by_user_id` bigint(20) unsigned DEFAULT NULL COMMENT 'staff que registro la cita',
  `appointment_date` date NOT NULL,
  `appointment_time` time NOT NULL,
  `reason` text DEFAULT NULL,
  `reprogramming` tinyint(1) DEFAULT 0,
  `status` enum('pendiente','confirmada','completada','cancelada') DEFAULT 'pendiente',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `service_id` (`service_id`),
  KEY `created_by_user_id` (`created_by_user_id`),
  KEY `idx_citas_vet_date` (`veterinarian_id`,`appointment_date`),
  KEY `idx_citas_pet` (`pet_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`veterinarian_id`) REFERENCES `users` (`id`),
  CONSTRAINT `3` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE SET NULL,
  CONSTRAINT `4` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `reminders`;

CREATE TABLE `reminders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `remindable_type` enum('cita','vacuna') NOT NULL,
  `remindable_id` bigint(20) unsigned NOT NULL,
  `remind_at` datetime NOT NULL,
  `message` varchar(255) DEFAULT NULL,
  `status` enum('pendiente','enviado','cancelado') DEFAULT 'pendiente',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pet_id` (`pet_id`),
  KEY `idx_remindable` (`remindable_type`,`remindable_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `surgiere`;

CREATE TABLE `surgiere` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `veterinarian_id` bigint(20) unsigned NOT NULL,
  `cita_id` bigint(20) unsigned DEFAULT NULL,
  `surgery_type` varchar(100) DEFAULT NULL,
  `surgery_date` datetime NOT NULL,
  `outcome` text DEFAULT NULL,
  `status` enum('pendiente','en_proceso','completada','cancelada') DEFAULT 'pendiente',
  `medical_notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pet_id` (`pet_id`),
  KEY `veterinarian_id` (`veterinarian_id`),
  KEY `cita_id` (`cita_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`veterinarian_id`) REFERENCES `users` (`id`),
  CONSTRAINT `3` FOREIGN KEY (`cita_id`) REFERENCES `citas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vacunas`;

CREATE TABLE `vacunas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `veterinarian_id` bigint(20) unsigned NOT NULL,
  `vaccine_type_id` bigint(20) unsigned NOT NULL,
  `cita_id` bigint(20) unsigned DEFAULT NULL,
  `vaccination_date` date NOT NULL,
  `vaccination_time` time DEFAULT NULL,
  `next_due_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pet_id` (`pet_id`),
  KEY `veterinarian_id` (`veterinarian_id`),
  KEY `vaccine_type_id` (`vaccine_type_id`),
  KEY `cita_id` (`cita_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`veterinarian_id`) REFERENCES `users` (`id`),
  CONSTRAINT `3` FOREIGN KEY (`vaccine_type_id`) REFERENCES `vaccine_types` (`id`),
  CONSTRAINT `4` FOREIGN KEY (`cita_id`) REFERENCES `citas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `medical_record`;

CREATE TABLE `medical_record` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `veterinarian_id` bigint(20) unsigned NOT NULL,
  `cita_id` bigint(20) unsigned DEFAULT NULL,
  `vaccination_id` bigint(20) unsigned DEFAULT NULL,
  `surgery_id` bigint(20) unsigned DEFAULT NULL,
  `event_type` enum('consulta','vacuna','cirugia','otro') NOT NULL,
  `event_date` date NOT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `veterinarian_id` (`veterinarian_id`),
  KEY `cita_id` (`cita_id`),
  KEY `vaccination_id` (`vaccination_id`),
  KEY `surgery_id` (`surgery_id`),
  KEY `idx_medical_record_pet` (`pet_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`veterinarian_id`) REFERENCES `users` (`id`),
  CONSTRAINT `3` FOREIGN KEY (`cita_id`) REFERENCES `citas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `4` FOREIGN KEY (`vaccination_id`) REFERENCES `vacunas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `5` FOREIGN KEY (`surgery_id`) REFERENCES `surgiere` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `medical_record_attachments`;

CREATE TABLE `medical_record_attachments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `medical_record_id` bigint(20) unsigned NOT NULL,
  `file_url` varchar(255) NOT NULL,
  `file_public_id` varchar(255) DEFAULT NULL,
  `file_type` varchar(30) DEFAULT NULL COMMENT 'image, pdf, etc.',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `medical_record_id` (`medical_record_id`),
  CONSTRAINT `1` FOREIGN KEY (`medical_record_id`) REFERENCES `medical_record` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `prescriptions`;

CREATE TABLE `prescriptions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `medical_record_id` bigint(20) unsigned NOT NULL,
  `medicine_id` bigint(20) unsigned NOT NULL,
  `dosage` varchar(60) NOT NULL,
  `duration_days` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `medical_record_id` (`medical_record_id`),
  KEY `medicine_id` (`medicine_id`),
  CONSTRAINT `1` FOREIGN KEY (`medical_record_id`) REFERENCES `medical_record` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`medicine_id`) REFERENCES `medicines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vital_signs`;

CREATE TABLE `vital_signs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `pet_id` bigint(20) unsigned NOT NULL,
  `medical_record_id` bigint(20) unsigned DEFAULT NULL,
  `weight` decimal(6,2) DEFAULT NULL,
  `temperature` decimal(4,1) DEFAULT NULL,
  `heart_rate` int(11) DEFAULT NULL,
  `recorded_at` datetime NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pet_id` (`pet_id`),
  KEY `medical_record_id` (`medical_record_id`),
  CONSTRAINT `1` FOREIGN KEY (`pet_id`) REFERENCES `pacientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `2` FOREIGN KEY (`medical_record_id`) REFERENCES `medical_record` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
